### ISSUE TITLE
MIssing configobj

### ISSUE THREAD

**Issue by dz0ny** [matgallacher/Mopidy-Material-Webclient#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 69, in main
    extensions_data = ext.load_extensions()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/ext.py", line 194, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_material_webclient/__init__.py", line 11, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj
```

**Comment by pastukhov** [comment]
Same for me

**Comment by jake-g** [comment]
pip install configobj

**Comment by maxanier** [comment]
Thanks @jake-g this fixed it for me.
@matgallacher can you add this information to the installation instructions? Thanks.
Cool webclient by the way :)

**Comment by matgallacher** [comment]
Added to the instructions for the meantime - apologies for not being around much at the moment, work is somewhat getting the better of me.

Glad to hear people are using it!
